---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tab-tutor-secrets
  namespace: tab-tutor
spec:
  encryptedData:
    GROQ_API_KEY: AgC5pNit48yrOD1750Bvn7PeHFUVn2t6gS9rrL9oO0PyFqys+mnOpB3IeGC58rlfd/fqbjICFBopoZ9Sn6r9IVfHi7IH5pUdGE/8qAy1/WbmbKDasantKP6ZgXHnGxKneRJWjXoNnv/iwCBMee23m+rL81aXKeXzMJ0waMgBYWOWp2FjTLIGFpzNetBDDx2QzxfW/Z1i/1bB56FdZu9ZLl9qGC9Ty2bfkpa9jL91L6JBJ+DzzvRlYdMIqgNH5/LgQ3Qdr3425ysiShK28ii8hzrRxGE8hBj0iU5eFcb2zt0F+uFhnWLSO+e3mJiSQtfaccKb+H6wUYwO1yLCOTNKeC+DsIo32NV6fAbVe82veMSRFzeMSpHFlUnkVQzwsfo+vKlmeiVwAlaUiBQ55GotzpFeANbIb1SadsWmb7lM1NsS5bMvqmTcmHbV4U0E/+E62vOoetL2JR2d8GnsQwmALSISwmQg+/ay8Ebruj3bUYHTyG95dIY31zmEw3sqnyCpb2zN1OrFZk5uodtKFGP7aSvPdStiaoFM8/4bOshujyTFtLdEDRxquhIUu5kLnVykoSKQ6owZ4jAnE2mzBzO173uyasiq2sP6F4HZjmin9bSGiz77oVHzPFZ1c+goBF6vhBH9PZ3j7A6E9Rkhgi+tcz9ao3ef5M1uJ1ZPR+ZueBOgiQRnQ4EqErHNkTMi7lOmVGHPAp+katkWD+xqjW6IzvV0mCtKVAf6/hGbBVXI0OWWOsVPa8RC1puPgGMrlDdXTtbsRO0Ud7k/Jw==
  template:
    metadata:
      creationTimestamp: null
      name: tab-tutor-secrets
      namespace: tab-tutor
