{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tab-tutor-secrets",
    "namespace": "tab-tutor",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tab-tutor-secrets",
        "namespace": "tab-tutor",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "GROQ_API_KEY": "AgC5pNit48yrOD1750Bvn7PeHFUVn2t6gS9rrL9oO0PyFqys+mnOpB3IeGC58rlfd/fqbjICFBopoZ9Sn6r9IVfHi7IH5pUdGE/8qAy1/WbmbKDasantKP6ZgXHnGxKneRJWjXoNnv/iwCBMee23m+rL81aXKeXzMJ0waMgBYWOWp2FjTLIGFpzNetBDDx2QzxfW/Z1i/1bB56FdZu9ZLl9qGC9Ty2bfkpa9jL91L6JBJ+DzzvRlYdMIqgNH5/LgQ3Qdr3425ysiShK28ii8hzrRxGE8hBj0iU5eFcb2zt0F+uFhnWLSO+e3mJiSQtfaccKb+H6wUYwO1yLCOTNKeC+DsIo32NV6fAbVe82veMSRFzeMSpHFlUnkVQzwsfo+vKlmeiVwAlaUiBQ55GotzpFeANbIb1SadsWmb7lM1NsS5bMvqmTcmHbV4U0E/+E62vOoetL2JR2d8GnsQwmALSISwmQg+/ay8Ebruj3bUYHTyG95dIY31zmEw3sqnyCpb2zN1OrFZk5uodtKFGP7aSvPdStiaoFM8/4bOshujyTFtLdEDRxquhIUu5kLnVykoSKQ6owZ4jAnE2mzBzO173uyasiq2sP6F4HZjmin9bSGiz77oVHzPFZ1c+goBF6vhBH9PZ3j7A6E9Rkhgi+tcz9ao3ef5M1uJ1ZPR+ZueBOgiQRnQ4EqErHNkTMi7lOmVGHPAp+katkWD+xqjW6IzvV0mCtKVAf6/hGbBVXI0OWWOsVPa8RC1puPgGMrlDdXTtbsRO0Ud7k/Jw==",
      "SPOTIFY_CLIENT_ID": "AgBvqAxcXUa0xGHc7E/V5PfuoqSXFXt+xzj8nIuHx/It6JFHZ2WVf704LzhQ3LAC8SDvxWsjH02jhcolNx+XOX+2zvqjSu/ncyswh2UYwTKQ3+KHXjHD3cq+BRmFnZheprBESpvTnG1qL7OrRcW+2+YXPyeEGdHqiUn8sL1qn7FAdbNNNoE0QGfLU75dj4wbQUVEl82fxa71YZ3HmQKoviSKqb6loCM36VIAxgBRu8akfThwqurH8+jjbdI1GSlDw4RyJByVNOTBpQfMEm3k5suWOfQOF0NQXhrR4wQ4Kne1L0U3TOVtayYWca9V2KJDwTZnPbB5LuEOisz2nGHCdJJJkBfCux+OmERh3CEngfT2XaVRTDPP8XmOcT/4IdCmNoThSbtT8I7SfAm1CipiTwpDbDbPUATvja7+Cx8mCrgMXmHiUOediLcJAz3xV6mxREQgyF4l02yfi+izqFmw+grVIf3oHfiwbNYwuZBhDq53iio8qCxQrbcB5ptassgAzJKUATpnR0n1zzomFFKWmKyEUdWI46sagC0gIfK+VLET3YlgOSYIrdKKNXqXb0wKk4skBS3ad7v2mYJUbO5oPTGf5+rpLISlgXv6Vnldd3mfzil4pRL080CyfSlTNz4/aohsTCIxCKeM399hze9c0lPV8SbV1kWzHYJqOxhxj+EBxq+Y6lRKPrrA4r4LfA4bZHaaWDWwtVqh+h3al+A3wOwcTReXDpxheehhNtTy0NEhGg==",
      "SPOTIFY_CLIENT_SECRET": "AgCe2WSZe3PRc3NwDcmLV2U2W3oSiZyAV/AuQXSMd6B/oFuRDD9g2REBrfRrQSPMCQhvKwMHOlLWaQ3VhYvnEukhjDfl5Zb9OEGWS6V3id3k9olVI0Iq8C7PKGGWd3OhtZyUPN8ZHonZ4BdJoJMewaNJoNUPO6QNjOAfy55J5AmuUvDqDQRcp5Dx7Lrhhd3c98cOobZQUhMp/qoCL2hq6bXu2MF4RmAqZk+A+lKTtXZFs/6Mo7HEfoN1E3ovhGmUC1/4XsEXPMaprziCsGLl8nu5kyEGBWzSSP5jch8P+GoR/K5C/x72wdoT7hT3j4fkEYtmC9Yn/LM2RCvIi14N55K6qCu2jzhPeWj+ArQwl0wBnaOUfFHHCLAT1hRVU0g9fCW7gfuxQpOMGUlJ1nnUGAt2ScNj8tGLUZy0Sf9DOnFk8bDQXaaIGMP31mO7ln4cjR4cBsCB9JGMI7Y7amTqEvX7Mt4EOHGBeNjAWkD/K8Uxp/7uMmIDHHSEDLwrqpM+NQuHLozCCkuQMs8c8J8bI+OiZ74WB/iZi2lhf5C/eicD3sdCff/U2Gjri0/YeXPsq+GU4NBG/SiYWmlX0EcAb25pokBF2YXS61FCSTvZeSpOUwU03PKtu/OM+X2wxfg/nHuwdtlPKeOf/7jKYjaFNwqUsng1YZZny4b8E+WBm6AL8WK8pNVa6A1yzJxXqkSY0qq0Q4dU97gvMBFiXJSD0IXmMARme/1bFia7D9xW1dELmw=="
    }
  }
}
